### ISSUE TITLE
acyl.yml local section

### ISSUE THREAD

**Issue by bkeroackdsc** [dollarshaveclub/acyl#170]
We should implement a new section in acyl.yml grammar to make the local workflow more convenient. In particular, we should provide an easy way to provide a custom set of value overrides for local use only, as well as a way to reduce CLI boilerplate (image build mode, search paths, etc).

Example mock up:

```yaml
# ...

local:
  privileged: true
  value_overrides:
    - 'foo=bar'
    - 'asdf=123'
  image_build_mode: docker-nopush
  search_paths:
    - ~/code/something
    - 
# ...
```

The local section should have defaults for all CLI flags for `acyl config test create/update/delete` commands.
