### ISSUE TITLE
acyl.yml: Helm chart repo option

### ISSUE THREAD

**Issue by bkeroackdsc** [dollarshaveclub/acyl#172]
Currently we support two ways to specify charts: `chart_repo_path` (GitHub repo + revision + path) and `chart_path` (path within triggering repo).

With modern Helm v3, it would be useful to support an additional option: Helm repo + chart name + chart version.

Unfortunately with the term "repo" being so heavily overloaded, we will need to find a clear way to distinguish between "the chart in this **GitHub** repository at this revision and path" and "the chart in this **Helm chart** repository with name X and version Y".

An example might be something like:

```yaml
# ...

application:
  helm_chart_repo:
    url: 'http://example.com/helm-charts'
    name: widgets
    version: 1.0.0
  image: 'foo/bar'
  value_overrides:
    - foo=bar
 # ...
```

In the above example, `application.helm_chart_repo.url` would be defined as the URL to the chart repository index (ex: "https://charts.bitnami.com/bitnami"). For convenience the user could omit the "index.yaml". All three values are required (url, name version).

Needs #169
